---

repos:

  - repo: git@github.com:pre-commit/pre-commit-hooks
    rev: master
    hooks:
      - id: flake8
        types: [file, python]
      - id: check-added-large-files
      - id: check-byte-order-marker
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-symlinks
      - id: debug-statements
        types: [file, python]
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: requirements-txt-fixer
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]

  - repo: https://github.com/pre-commit/mirrors-isort
    rev: master
    hooks:
      - id: isort
        types: [file, python]
